### ISSUE TITLE
Loot tables in QOL not working.

### ISSUE THREAD

**Issue by osera89** [Yasser444o/Skybedrock#3]
I have an issue with skybedrock where zombies, blaze, zombie piglin and wither skeleton doesnt drop the assign loot tables, havent progress so far yet, dont know about any other features, im playing on an adroid phone by the way, thanks for the help.

**Comment by Yasser4440** [comment]
could you provide screenshots of the world behavior packs and resource packs.

**Comment by Yasser4440** [comment]
Hi, i did test it again in Android and with the same conditions you described and zombies dropped gravel 
![Screenshot_20240317-044231_Minecraft](https://github.com/Yasser444o/Skybedrock/assets/85234823/9c4641b4-31a8-4c2b-9b64-b7fb95d1241a)
i am pretty sure the issue is from your side, make sure to download the map from the link i provided and make sure its version is 1.20.9 or higher.

**Comment by Yasser444o** [comment]
could you provide screenshots of the world behavior packs and resource packs.

**Comment by Yasser444o** [comment]
conditions you described and zombies dropped gravel
![Screenshot_20240317-044231_Minecraft](https://github.com/Yasser444o/Skybedrock/assets/157912825/46412f10-eee5-43d9-b72e-93557901f55b)

i am pretty sure the issue is from your side, make sure to download the map from the link i provided and make sure its version is 1.20.9 or higher.

**Comment by Yasser4440** [comment]
test

**Comment by osera89** [comment]
Hi, here are the screenshots..
![Screenshot_2024-03-18-13-23-18-62_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/Yasser444o/Skybedrock/assets/146631984/44f07569-e9d9-4c90-8fcb-cfc0715f96fe)

![Screenshot_2024-03-18-13-23-22-38_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/Yasser444o/Skybedrock/assets/146631984/ab894d67-182f-4830-a30f-8a73d6e38625)

![Screenshot_2024-03-18-13-23-10-34_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/Yasser444o/Skybedrock/assets/146631984/c7bf518d-123d-4098-8f20-9fd9bb4bb12f)

![Screenshot_2024-03-18-13-21-52-58_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/Yasser444o/Skybedrock/assets/146631984/5ec9ee83-32eb-4c3b-b20f-1651e0ac33db)

**Comment by Yasser444o** [comment]
ok, if you have access to your Android/data folder, i want you to send me a copy of the world. so i can diagnose it closely.

**Comment by osera89** [comment]
Ok thanks for the response, I will send the file later when I get home.. thanks

**Comment by osera89** [comment]
Hello, I've manage to extract my world from my device into the pc in the form of  .mcworld. Sorry it took so long, but here is the world. Please kindly check.
[Skybedrock - Copy.zip](https://github.com/Yasser444o/Skybedrock/files/14636796/Skybedrock.-.Copy.zip)

**Comment by Yasser444o** [comment]
Hello, i viewed your world and apparently nothing's wrong with it, i killed the zombies in your mob grinder and they dropped gravel as intended as you can see
![Screenshot_20240319-014016_Minecraft.jpg](https://github.com/Yasser444o/Skybedrock/assets/157912825/acea71b8-2b90-41fa-9456-947cfc42e093)

I don't know what causes it for you, do you have Minecraft on any other devices? you might want to try it in a different device, this might help you know what's wrong.
